/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'slug' : string,
  'description' : string,
}
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : string,
  'author' : string,
  'readingTimeMinutes' : bigint,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface _SERVICE {
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCategoryBySlug' : ActorMethod<[string], Category>,
  'getPostBySlug' : ActorMethod<[string], Post>,
  'getPostsByCategory' : ActorMethod<[string], Array<Post>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];